// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1zaSMbQKW__sHsl8l68vD-H3bW_RduA',
    appId: '1:782175923688:web:bafdeed95136a9cc4c485d',
    messagingSenderId: '782175923688',
    projectId: 'smartbo-bfaa0',
    authDomain: 'smartbo-bfaa0.firebaseapp.com',
    storageBucket: 'smartbo-bfaa0.firebasestorage.app',
    measurementId: 'G-H0VDL0VP17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9WSOT7fwWxjKNRSr8-04MMWJn5fHBSo',
    appId: '1:782175923688:android:ac907b099e9d5e2c4c485d',
    messagingSenderId: '782175923688',
    projectId: 'smartbo-bfaa0',
    storageBucket: 'smartbo-bfaa0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQKgalLeSmFflHucEfic3GzgIppSa8XJQ',
    appId: '1:782175923688:ios:df74bcdaf279cf714c485d',
    messagingSenderId: '782175923688',
    projectId: 'smartbo-bfaa0',
    storageBucket: 'smartbo-bfaa0.firebasestorage.app',
    iosBundleId: 'com.example.smartbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd1zaSMbQKW__sHsl8l68vD-H3bW_RduA',
    appId: '1:782175923688:web:db54374d8825011b4c485d',
    messagingSenderId: '782175923688',
    projectId: 'smartbo-bfaa0',
    authDomain: 'smartbo-bfaa0.firebaseapp.com',
    storageBucket: 'smartbo-bfaa0.firebasestorage.app',
    measurementId: 'G-5FYMC7YS9Q',
  );
}
